version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

metamask: &metamask
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install chrome driver
        command: |
          sudo apt-get install libnss3 libgconf-2-4
          wget -N http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/bin
          sudo ln -s /usr/bin/google-chrome-stable /usr/bin/chrome
          chromedriver --version
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tests
        command: |
          ~/.local/bin/tox -e $TOXENV --notest
          source ~/repo/.tox/$TOXENV/bin/activate
          pytest tests/integration/metamask/
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  doctest:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV: doctest
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV: lint
  # python 3.5
  py35-core:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV: py35-core
  py35-integration-web3:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV: py35-integration-web3
  # python 3.6
  py36-core:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-core
  py36-integration-web3:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-integration-web3
  py36-integration-metamask:
    <<: *metamask
    docker:
      - image: circleci/python:3.6-browsers
        environment:
          TOXENV: py36-integration-metamask
  # python3.7
  py37-core:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-core
  py37-integration-web3:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-integration-web3
  # pypy
  pypy3-core:
    <<: *common
    docker:
      - image: pypy
        environment:
          TOXENV: pypy3-core
  pypy3-integration-web3:
    <<: *common
    docker:
      - image: pypy
        environment:
          TOXENV: pypy3-integration-web3
workflows:
  version: 2
  test:
    jobs:
      - doctest
      - lint
      - py35-core
      - py35-integration-web3
      - py36-core
      - py36-integration-web3
      - py36-integration-metamask
      - py37-core
      - py37-integration-web3
      - pypy3-core
      - pypy3-integration-web3
